Friend Module EndPoints
    'Twitter
    Friend ReadOnly Twitter_REST As String = "https://api.twitter.com/1.1/"
    Friend ReadOnly Twitter_API As String = "https://api.twitter.com/"
    'Oauth
    Friend ReadOnly Oauth_request_token As String = EndPoints.Twitter_API & "oauth/request_token"
    Friend ReadOnly Oauth_Authorize As String = EndPoints.Twitter_API & "oauth/authorize"
    Friend ReadOnly Oauth_Access_token As String = EndPoints.Twitter_API & "oauth/access_token"
    'Timeline
    Friend ReadOnly Statuses_HomeTL As String = EndPoints.Twitter_REST & "statuses/home_timeline.json"
    Friend ReadOnly Statuses_Mentions As String = EndPoints.Twitter_REST & "statuses/mentions_timeline.json"
    Friend ReadOnly Statuses_UserTL As String = EndPoints.Twitter_REST & "statuses/user_timeline.json"
    Friend ReadOnly Statuses_Retweets_of_me As String = EndPoints.Twitter_REST & "statuses/retweets_of_me.json"
    'Statuses
    Friend ReadOnly Statuses_Retweets As String = EndPoints.Twitter_REST & "statuses/retweets/{0}.json"
    Friend ReadOnly Statuses_Show As String = EndPoints.Twitter_REST & "statuses/show.json"
    Friend ReadOnly Statuses_Destroy As String = EndPoints.Twitter_REST & "statuses/destroy/{0}.json"
    Friend ReadOnly Statuses_Update As String = EndPoints.Twitter_REST & "statuses/update.json"
    Friend ReadOnly Statuses_Retweet As String = EndPoints.Twitter_REST & "statuses/retweet/{0}.json"
    Friend ReadOnly Statuses_Oembed As String = EndPoints.Twitter_REST & "statuses/oembed.json"
    Friend ReadOnly Statuses_Retweeters_Ids As String = EndPoints.Twitter_REST & "statuses/retweeters/ids.json"
    Friend ReadOnly Statuses_Update_With_Media As String = EndPoints.Twitter_REST & "statuses/update_with_media.json"
    'Search
    Friend ReadOnly Search_Tweets As String = EndPoints.Twitter_REST & "search/tweets.json"
    'DirectMessages
    Friend ReadOnly Direct_Messages As String = EndPoints.Twitter_REST & "direct_messages.json"
    Friend ReadOnly Direct_Messages_Sent As String = EndPoints.Twitter_REST & "direct_messages/sent.json"
    Friend ReadOnly Direct_Messsages_Show As String = EndPoints.Twitter_REST & "direct_messages/show.json"
    Friend ReadOnly Direct_Messages_Destroy As String = EndPoints.Twitter_REST & "direct_messages/destroy.json"
    Friend ReadOnly Direct_Messages_New As String = EndPoints.Twitter_REST & "direct_messages/new.json"
    'FriendShips
    Friend ReadOnly FriendShips_NoRetweets_Ids As String = EndPoints.Twitter_REST & "friendships/no_retweets/ids.json"
    Friend ReadOnly Friends_Ids As String = EndPoints.Twitter_REST & "friends/ids.json"
    Friend ReadOnly Followers_Ids As String = EndPoints.Twitter_REST & "followers/ids.json"
    Friend ReadOnly FriendShips_Lookup As String = EndPoints.Twitter_REST & "friendships/lookup.json"
    Friend ReadOnly FriendShips_Incoming As String = EndPoints.Twitter_REST & "friendships/incoming.json"
    Friend ReadOnly FriendShips_Outgoing As String = EndPoints.Twitter_REST & "friendships/outgoing.json"
    Friend ReadOnly FriendShips_Create As String = EndPoints.Twitter_REST & "friendships/create.json"
    Friend ReadOnly FriendShips_Destroy As String = EndPoints.Twitter_REST & "friendships/destroy.json"
    Friend ReadOnly FriendShips_Update As String = EndPoints.Twitter_REST & "friendships/update.json"
    Friend ReadOnly FriendShips_Show As String = EndPoints.Twitter_REST & "friendships/show.json"
    Friend ReadOnly Friend_List As String = EndPoints.Twitter_REST & "friends/list.json"
    Friend ReadOnly Followers_List As String = EndPoints.Twitter_REST & "followers/list.json"
    'Account
    Friend ReadOnly Account_Setting As String = EndPoints.Twitter_REST & "account/settings.json"
    Friend ReadOnly Account_Verify_Credentials As String = EndPoints.Twitter_REST & "account/verify_credentials.json"
    Friend ReadOnly Account_Update_Profile As String = EndPoints.Twitter_REST & "account/update_profile.json"
    Friend ReadOnly Account_Update_Profile_Colors As String = EndPoints.Twitter_REST & "account/update_profile_colors.json"
    Friend ReadOnly Account_Update_Profile_Background_Image As String = EndPoints.Twitter_REST & "account/update_profile_background_image.json"
    Friend ReadOnly Account_Update_Profile_Image As String = EndPoints.Twitter_REST & "account/update_profile_image.json"
    Friend ReadOnly Account_Remove_Profile_Banner As String = EndPoints.Twitter_REST & "account/remove_profile_banner.json"
    Friend ReadOnly Account_Update_Profile_Banner As String = EndPoints.Twitter_REST & "account/update_profile_banner.json"
    Friend ReadOnly Application_Rate_Limit_Status As String = EndPoints.Twitter_REST & "application/rate_limit_status.json"
    'Blocks
    Friend ReadOnly Blocks_List As String = EndPoints.Twitter_REST & "blocks/list.json"
    Friend ReadOnly Blocks_Ids As String = EndPoints.Twitter_REST & "blocks/ids.json"
    Friend ReadOnly Blocks_Create As String = EndPoints.Twitter_REST & "blocks/create.json"
    Friend ReadOnly Blocks_Destroy As String = EndPoints.Twitter_REST & "blocks/destroy.json"
    'Users
    Friend ReadOnly Users_Lookup As String = EndPoints.Twitter_REST & "users/lookup.json"
    Friend ReadOnly Users_Show As String = EndPoints.Twitter_REST & "users/show.json"
    Friend ReadOnly Users_Search As String = EndPoints.Twitter_REST & "users/search.json"
    Friend ReadOnly Users_Contributees As String = EndPoints.Twitter_REST & "users/contributees.json"
    Friend ReadOnly Users_Contributors As String = EndPoints.Twitter_REST & "users/contributors.json"
    Friend ReadOnly Users_Report_Spam As String = EndPoints.Twitter_REST & "users/report_spam.json"
    'Favorites
    Friend ReadOnly Favorites_List As String = EndPoints.Twitter_REST & "favorites/list.json"
    Friend ReadOnly Favorites_Destroy As String = EndPoints.Twitter_REST & "favorites/destroy.json"
    Friend ReadOnly Favorite_Create As String = EndPoints.Twitter_REST & "favorites/create.json"
    'Lists
    Friend ReadOnly Lists_List As String = EndPoints.Twitter_REST & "lists/list.json"
    Friend ReadOnly Lists_Statuses As String = EndPoints.Twitter_REST & "lists/statuses.json"
    Friend ReadOnly Lists_Members_Destroy As String = EndPoints.Twitter_REST & "lists/members/destroy.json"
    Friend ReadOnly Lists_Memberships As String = EndPoints.Twitter_REST & "lists/memberships.json"
    Friend ReadOnly Lists_Ownerships As String = EndPoints.Twitter_REST & "lists/ownerships.json"
    Friend ReadOnly Lists_Subscribers As String = EndPoints.Twitter_REST & "lists/subscribers.json"
    Friend ReadOnly Lists_Subscribers_Create As String = EndPoints.Twitter_REST & "lists/subscribers/create.json"
    Friend ReadOnly Lists_Subscribers_Show As String = EndPoints.Twitter_REST & "lists/subscribers/show.json"
    Friend ReadOnly Lists_Subscribers_Destroy As String = EndPoints.Twitter_REST & "lists/subscribers/destroy.json"
    Friend ReadOnly Lists_Members_Create_All As String = EndPoints.Twitter_REST & "lists/members/create_all.json"
    Friend ReadOnly Lists_Members_Show As String = EndPoints.Twitter_REST & "lists/members/show.json"
    Friend ReadOnly Lists_Members As String = EndPoints.Twitter_REST & "lists/members.json"
    Friend ReadOnly Lists_Members_Create As String = EndPoints.Twitter_REST & "lists/members/create.json"
    Friend ReadOnly Lists_Destroy As String = EndPoints.Twitter_REST & "lists/destroy.json"
    Friend ReadOnly Lists_Update As String = EndPoints.Twitter_REST & "lists/update.json"
    Friend ReadOnly Lists_Create As String = EndPoints.Twitter_REST & "lists/create.json"
    Friend ReadOnly Lists_Show As String = EndPoints.Twitter_REST & "lists/show.json"
    Friend ReadOnly Lists_Subscriptions As String = EndPoints.Twitter_REST & "lists/subscriptions.json"
    Friend ReadOnly Lists_Members_Destroy_All As String = EndPoints.Twitter_REST & "members/destroy_all.json"
    'SavedSearches
    Friend ReadOnly Saved_Searches_List As String = EndPoints.Twitter_REST & "saved_searches/list.json"
    Friend ReadOnly Saved_Searches_Show_Id As String = EndPoints.Twitter_REST & "saved_searches/show/{0}.json"
    Friend ReadOnly Saved_Searches_Create As String = EndPoints.Twitter_REST & "saved_searches/create.json"
    Friend ReadOnly Saved_Searches_Destroy_Id As String = EndPoints.Twitter_REST & "saved_searches/destroy/{0}.json"
    'Geo
    Friend ReadOnly Geo_Id_PlaceId As String = EndPoints.Twitter_REST & "geo/id/{0}.json"
    Friend ReadOnly Geo_Reverse_Geocode As String = EndPoints.Twitter_REST & "geo/reverse_geocode.json"
    Friend ReadOnly Geo_Search As String = EndPoints.Twitter_REST & "geo/search.json"
    Friend ReadOnly Geo_Similar_Places As String = EndPoints.Twitter_REST & "geo/similar_places.json"
    'Trends
    Friend ReadOnly Trends_Place As String = EndPoints.Twitter_REST & "trends/place.json"
    Friend ReadOnly Trends_Available As String = EndPoints.Twitter_REST & "trends/available.json"
    Friend ReadOnly Trends_Closest As String = EndPoints.Twitter_REST & "trends/closest.json"
    'Help
    Friend ReadOnly Help_Configuration As String = EndPoints.Twitter_REST & "help/configuration.json"
    Friend ReadOnly Help_Languages As String = EndPoints.Twitter_REST & "help/languages.json"
    Friend ReadOnly Help_Privacy As String = EndPoints.Twitter_REST & "help/privacy.json"
    Friend ReadOnly Help_Tos As String = EndPoints.Twitter_REST & "help/tos.json"
End Module
